// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0X5YmE2jIk6hxdfYY11aMd3U9Fyyr9xc',
    appId: '1:889327520077:web:2bd0fee034e9faefc08f04',
    messagingSenderId: '889327520077',
    projectId: 'snpcompany-a1d73',
    authDomain: 'snpcompany-a1d73.firebaseapp.com',
    storageBucket: 'snpcompany-a1d73.appspot.com',
    measurementId: 'G-NPC9RT3BG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6Z2lcoywPQSAvonahkyD-2NTyAZjcow',
    appId: '1:889327520077:android:668b62dd5e2a1795c08f04',
    messagingSenderId: '889327520077',
    projectId: 'snpcompany-a1d73',
    storageBucket: 'snpcompany-a1d73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ1DmUAdo5JM_QF-KG_bjDFeVgoQ0N1k0',
    appId: '1:889327520077:ios:f9309dad1f7e4849c08f04',
    messagingSenderId: '889327520077',
    projectId: 'snpcompany-a1d73',
    storageBucket: 'snpcompany-a1d73.appspot.com',
    iosClientId: '889327520077-kjifodmk9keklh7jv6rrblcjo1pdtf07.apps.googleusercontent.com',
    iosBundleId: 'com.example.snpBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ1DmUAdo5JM_QF-KG_bjDFeVgoQ0N1k0',
    appId: '1:889327520077:ios:f9309dad1f7e4849c08f04',
    messagingSenderId: '889327520077',
    projectId: 'snpcompany-a1d73',
    storageBucket: 'snpcompany-a1d73.appspot.com',
    iosClientId: '889327520077-kjifodmk9keklh7jv6rrblcjo1pdtf07.apps.googleusercontent.com',
    iosBundleId: 'com.example.snpBookingApp',
  );
}
